services:
  nilabiru-portainer-agent:
    image: portainer/agent:latest
    container_name: nilabiru-portainer-agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - nilabiru-data-hub-frps

  nilabiru-frps:
    image: fatedier/frps:v0.69.1
    container_name: nilabiru-frps
    restart: unless-stopped
    command: ["-c", "/etc/frp/frps.toml"]
    ports:
      - "7000:7000"
      - "80:80"
      - "443:443"
      - "7500:7500"
    volumes:
      - ./frps.toml:/etc/frp/frps.toml:ro
    networks:
      - nilabiru-data-hub-frps

networks:
  nilabiru-data-hub-frps:
    driver: bridge
